services:

  openfga:
    image: openfga/openfga:latest
    container_name: openfga-server
    environment:
      - OPENFGA_DATASTORE_ENGINE=memory
      - OPENFGA_LOG_LEVEL=info
    command: run
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # gRPC
      - "3001:3001" # Playground
